/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package alexanderitesyaml

import groovy.yaml.YamlSlurper

class App {
    static void main(String[] args) {
        def multiDocYaml = '''\
---
drummer: Peart
---
bassist: Lee
'''

        def multiDoc = new YamlSlurper().parseText(multiDocYaml.replaceAll('---', ''))

        println multiDoc.drummer
        println multiDoc.bassist
    }
}
